In [2]:
import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests
import time

# Big 10 Scrape

In [3]:
base_url = "https://www.sports-reference.com/cbb/conferences/big-ten/men/{}-stats.html"

# years to scrape
years = list(range(2003, 2024))  # 2003 to 2023

# columns to scrape
columns = ["Player", "Team", "Pos", 'PTS', 'AST', "TRB", 'ORB', 'DRB', 
'STL', 'BLK', 'TOV', "G", "MP", "FG", "FGA", "FG%", "eFG%", 'FT', 'FTA', 'FT%']

# empty DataFrame to hold all data
all_data = pd.DataFrame()

In [4]:
# Loop through each year and scrape data
for year in years:
    url = base_url.format(year)
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html.parser")
    
    # Find the table
    tables = soup.find_all('table')
    
    # read table into a dataframe
    df = pd.read_html(str(tables))[0]
    
    
    # select columns 
    df = df[columns]
    
    # add a column for year
    df["Year"] = year
    
    # append to main DataFrame
    all_data = pd.concat([all_data, df])
    
    # rate limiting so I don't break this server
    time.sleep(1)

# Reset the index of the final DataFrame
all_data.reset_index(drop=True, inplace=True)

/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]
/var/folders/_6/yfw0v_fd27l4wlzfqpq38b7m0000gn/T/ipykernel_1502/971916482.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[0]

In [5]:
all_data

,Player,Team,Pos,PTS,AST,TRB,ORB,DRB,STL,BLK,...,G,MP,FG,FGA,FG%,eFG%,FT,FTA,FT%,Year
0,Brian Cook,Illinois,F,20.0,2.0,7.6,1.5,6.1,0.7,0.4,...,30.0,31.3,6.7,14.1,0.479,0.511,5.6,6.8,0.820,2003
1,Brent Darby,Ohio State,G,18.3,4.4,3.9,0.5,3.3,1.8,0.1,...,32.0,38.1,5.1,13.5,0.378,0.442,6.4,7.9,0.810,2003
2,Willie Deane,Purdue,G,17.8,2.2,5.0,0.8,4.3,1.7,0.2,...,30.0,28.8,5.5,13.1,0.417,0.478,5.3,6.7,0.782,2003
3,Bracey Wright,Indiana,G,16.2,2.1,5.0,1.4,3.6,0.8,0.6,...,30.0,33.6,5.2,12.1,0.433,0.523,3.5,4.7,0.752,2003
4,LaVell Blanchard,Michigan,F,16.2,1.0,6.8,1.9,5.0,0.6,0.3,...,30.0,32.0,5.2,12.4,0.422,0.511,3.5,4.3,0.814,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3652,Sam King,Purdue,F,0.0,0.0,0.3,0.0,0.3,0.0,0.0,...,4.0,1.8,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3653,Andrew Fulin,Rutgers,F,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3654,Isaac Gard,Wisconsin,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,1.0,0.0,0.2,0.000,0.000,0.0,0.0,NaN,2023
3655,Justin Taphorn,Wisconsin,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,1.2,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3656,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.448,0.511,NaN,NaN,0.713,2023

In [6]:
season_avg_df = all_data[all_data['Player'] != 'League Average']

In [7]:
season_avg_df

,Player,Team,Pos,PTS,AST,TRB,ORB,DRB,STL,BLK,...,G,MP,FG,FGA,FG%,eFG%,FT,FTA,FT%,Year
0,Brian Cook,Illinois,F,20.0,2.0,7.6,1.5,6.1,0.7,0.4,...,30.0,31.3,6.7,14.1,0.479,0.511,5.6,6.8,0.820,2003
1,Brent Darby,Ohio State,G,18.3,4.4,3.9,0.5,3.3,1.8,0.1,...,32.0,38.1,5.1,13.5,0.378,0.442,6.4,7.9,0.810,2003
2,Willie Deane,Purdue,G,17.8,2.2,5.0,0.8,4.3,1.7,0.2,...,30.0,28.8,5.5,13.1,0.417,0.478,5.3,6.7,0.782,2003
3,Bracey Wright,Indiana,G,16.2,2.1,5.0,1.4,3.6,0.8,0.6,...,30.0,33.6,5.2,12.1,0.433,0.523,3.5,4.7,0.752,2003
4,LaVell Blanchard,Michigan,F,16.2,1.0,6.8,1.9,5.0,0.6,0.3,...,30.0,32.0,5.2,12.4,0.422,0.511,3.5,4.3,0.814,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3651,Ishaan Jagiasi,Penn State,G,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3652,Sam King,Purdue,F,0.0,0.0,0.3,0.0,0.3,0.0,0.0,...,4.0,1.8,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3653,Andrew Fulin,Rutgers,F,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3654,Isaac Gard,Wisconsin,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,1.0,0.0,0.2,0.000,0.000,0.0,0.0,NaN,2023
3655,Justin Taphorn,Wisconsin,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,1.2,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023

In [8]:
season_avg_df.columns

Index(['Player', 'Team', 'Pos', 'PTS', 'AST', 'TRB', 'ORB', 'DRB', 'STL',
       'BLK', 'TOV', 'G', 'MP', 'FG', 'FGA', 'FG%', 'eFG%', 'FT', 'FTA', 'FT%',
       'Year'],
      dtype='object')

In [9]:
new_column = ['Player', 'Team', 'Pos', 'PTS', 'AST', 'TRB', 'ORB', 'DRB',
       'STL', 'BLK', 'TOV', 'G', 'MP', 'FG', 'FGA', 'FG%', 'eFG%', 'FT', 'FTA',
       'FT%', 'Year']

In [10]:
new_column = [column.lower() for column in new_column]

In [11]:
season_avg_df.columns = new_column

In [12]:
season_avg_df

,player,team,pos,pts,ast,trb,orb,drb,stl,blk,...,g,mp,fg,fga,fg%,efg%,ft,fta,ft%,year
0,Brian Cook,Illinois,F,20.0,2.0,7.6,1.5,6.1,0.7,0.4,...,30.0,31.3,6.7,14.1,0.479,0.511,5.6,6.8,0.820,2003
1,Brent Darby,Ohio State,G,18.3,4.4,3.9,0.5,3.3,1.8,0.1,...,32.0,38.1,5.1,13.5,0.378,0.442,6.4,7.9,0.810,2003
2,Willie Deane,Purdue,G,17.8,2.2,5.0,0.8,4.3,1.7,0.2,...,30.0,28.8,5.5,13.1,0.417,0.478,5.3,6.7,0.782,2003
3,Bracey Wright,Indiana,G,16.2,2.1,5.0,1.4,3.6,0.8,0.6,...,30.0,33.6,5.2,12.1,0.433,0.523,3.5,4.7,0.752,2003
4,LaVell Blanchard,Michigan,F,16.2,1.0,6.8,1.9,5.0,0.6,0.3,...,30.0,32.0,5.2,12.4,0.422,0.511,3.5,4.3,0.814,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3651,Ishaan Jagiasi,Penn State,G,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3652,Sam King,Purdue,F,0.0,0.0,0.3,0.0,0.3,0.0,0.0,...,4.0,1.8,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3653,Andrew Fulin,Rutgers,F,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023
3654,Isaac Gard,Wisconsin,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,1.0,0.0,0.2,0.000,0.000,0.0,0.0,NaN,2023
3655,Justin Taphorn,Wisconsin,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,1.2,0.0,0.0,NaN,NaN,0.0,0.0,NaN,2023

In [13]:
numeric_columns = ['pts', 'ast','trb', 'orb','drb', 'stl',
 'blk','tov','g','mp','fg','fga','fg%','efg%','ft','fta','ft%']

In [14]:
career_avg_df = season_avg_df.groupby('player').agg(
    {column: 'mean' for column in numeric_columns}
).reset_index()

In [15]:
career_avg_df = career_avg_df.round(2)

In [16]:
career_avg_df = career_avg_df.sort_values(by = 'pts', ascending = False).reset_index(drop = True)

In [17]:
big_10_career_avg_df = career_avg_df

In [18]:
big_10_career_avg_df

,player,pts,ast,trb,orb,drb,stl,blk,tov,g,mp,fg,fga,fg%,efg%,ft,fta,ft%
0,Kris Humphries,21.70,0.7,10.10,3.10,7.00,0.9,1.10,2.80,29.0,34.10,7.6,17.20,0.44,0.46,5.90,7.90,0.74
1,Eric Gordon Jr,20.90,2.4,3.30,0.70,2.50,1.3,0.60,3.60,32.0,34.70,5.8,13.30,0.43,0.52,7.20,8.70,0.83
2,Brian Cook,20.00,2.0,7.60,1.50,6.10,0.7,0.40,2.80,30.0,31.30,6.7,14.10,0.48,0.51,5.60,6.80,0.82
3,D'Angelo Russell,19.30,5.0,5.70,1.00,4.70,1.6,0.30,2.90,35.0,33.90,6.6,14.70,0.45,0.54,3.40,4.50,0.76
4,James Palmer,18.45,3.0,4.30,1.15,3.10,1.2,0.45,2.15,34.5,33.10,5.7,14.25,0.41,0.46,5.45,7.25,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536,Justin Hamilton,0.00,0.0,0.00,0.00,0.00,1.0,0.00,0.00,1.0,0.00,0.0,0.00,NaN,NaN,0.00,0.00,NaN
1537,Dylan Sandhu,0.00,0.0,0.15,0.00,0.15,0.0,0.00,0.00,3.0,0.65,0.0,0.15,0.00,0.00,0.00,0.00,NaN
1538,Spencer Barks,0.00,0.0,0.40,0.00,0.40,0.0,0.00,0.00,5.0,1.60,0.0,0.20,0.00,0.00,0.00,0.40,0.00
1539,Edgar Padilla Jr.,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,6.0,1.50,0.0,0.20,0.00,0.00,0.00,0.00,NaN
1540,Colin Dill,0.00,0.1,0.15,0.00,0.00,0.0,0.00,0.10,7.0,1.75,0.0,0.35,0.00,0.00,0.00,0.10,0.00

In [20]:
career_avg_df['mp'].mean(), career_avg_df['g'].mean()

(np.float64(14.97487345879299), np.float64(22.74369240752758))

In [21]:
career_avg_df = career_avg_df[career_avg_df['g'] > 20]
career_avg_df = career_avg_df[career_avg_df['mp'] > 15]

In [22]:
career_avg_df

,player,pts,ast,trb,orb,drb,stl,blk,tov,g,mp,fg,fga,fg%,efg%,ft,fta,ft%
0,Kris Humphries,21.70,0.70,10.10,3.10,7.00,0.90,1.10,2.80,29.00,34.10,7.60,17.20,0.44,0.46,5.90,7.90,0.74
1,Eric Gordon Jr,20.90,2.40,3.30,0.70,2.50,1.30,0.60,3.60,32.00,34.70,5.80,13.30,0.43,0.52,7.20,8.70,0.83
2,Brian Cook,20.00,2.00,7.60,1.50,6.10,0.70,0.40,2.80,30.00,31.30,6.70,14.10,0.48,0.51,5.60,6.80,0.82
3,D'Angelo Russell,19.30,5.00,5.70,1.00,4.70,1.60,0.30,2.90,35.00,33.90,6.60,14.70,0.45,0.54,3.40,4.50,0.76
4,James Palmer,18.45,3.00,4.30,1.15,3.10,1.20,0.45,2.15,34.50,33.10,5.70,14.25,0.41,0.46,5.45,7.25,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,Xavier Green,2.30,0.90,2.50,0.70,1.80,0.50,0.10,0.50,32.00,19.80,0.80,2.30,0.38,0.46,0.30,0.50,0.60
941,Ethan Morton,2.27,1.57,1.70,0.27,1.43,0.50,0.23,0.67,31.67,16.20,0.73,2.13,0.35,0.45,0.37,0.53,0.67
942,Michael Jenkins,2.27,1.30,1.60,0.33,1.27,0.80,0.10,0.77,24.33,15.13,0.77,2.00,0.35,0.44,0.40,0.63,0.48
997,Mike Turner,1.90,1.80,2.00,0.70,1.30,0.60,0.60,0.90,32.00,15.80,0.80,2.20,0.34,0.38,0.20,0.40,0.58
1070,Zach McRoberts,1.47,0.87,2.33,0.67,1.63,0.73,0.10,0.40,28.33,15.63,0.53,1.40,0.36,0.44,0.17,0.23,0.84

In [19]:
career_avg_df.to_csv('big_10_career_avg_.csv')