In [1]:
import pandas as pd

In [2]:
from nba_api.stats.endpoints import playercareerstats as nba_stats
from nba_api.stats.static import players as nba_players

In [3]:
from nba_api.stats.endpoints import drafthistory

In [4]:
draft = drafthistory.DraftHistory

In [5]:
draft

nba_api.stats.endpoints.drafthistory.DraftHistory

Limit the scope of the project to active players

In [6]:
pro_players = nba_players.get_active_players()

In [7]:
pro_players

[{'id': 1630173,
  'full_name': 'Precious Achiuwa',
  'first_name': 'Precious',
  'last_name': 'Achiuwa',
  'is_active': True},
 {'id': 1628389,
  'full_name': 'Bam Adebayo',
  'first_name': 'Bam',
  'last_name': 'Adebayo',
  'is_active': True},
 {'id': 1630534,
  'full_name': 'Ochai Agbaji',
  'first_name': 'Ochai',
  'last_name': 'Agbaji',
  'is_active': True},
 {'id': 1630583,
  'full_name': 'Santi Aldama',
  'first_name': 'Santi',
  'last_name': 'Aldama',
  'is_active': True},
 {'id': 1629638,
  'full_name': 'Nickeil Alexander-Walker',
  'first_name': 'Nickeil',
  'last_name': 'Alexander-Walker',
  'is_active': True},
 {'id': 1628960,
  'full_name': 'Grayson Allen',
  'first_name': 'Grayson',
  'last_name': 'Allen',
  'is_active': True},
 {'id': 1628386,
  'full_name': 'Jarrett Allen',
  'first_name': 'Jarrett',
  'last_name': 'Allen',
  'is_active': True},
 {'id': 1641851,
  'full_name': 'Timmy Allen',
  'first_name': 'Timmy',
  'last_name': 'Allen',
  'is_active': True},
 {'id': 1630631,
  'full_name': 'Jose Alvarado',
  'first_name': 'Jose',
  'last_name': 'Alvarado',
  'is_active': True},
 {'id': 203937,
  'full_name': 'Kyle Anderson',
  'first_name': 'Kyle',
  'last_name': 'Anderson',
  'is_active': True},
 {'id': 203507,
  'full_name': 'Giannis Antetokounmpo',
  'first_name': 'Giannis',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 203648,
  'full_name': 'Thanasis Antetokounmpo',
  'first_name': 'Thanasis',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 1630175,
  'full_name': 'Cole Anthony',
  'first_name': 'Cole',
  'last_name': 'Anthony',
  'is_active': True},
 {'id': 1628384,
  'full_name': 'OG Anunoby',
  'first_name': 'OG',
  'last_name': 'Anunoby',
  'is_active': True},
 {'id': 1627853,
  'full_name': 'Ryan Arcidiacono',
  'first_name': 'Ryan',
  'last_name': 'Arcidiacono',
  'is_active': True},
 {'id': 1630166,
  'full_name': 'Deni Avdija',
  'first_name': 'Deni',
  'last_name': 'Avdija',
  'is_active': True},
 {'id': 1629028,
  'full_name': 'Deandre Ayton',
  'first_name': 'Deandre',
  'last_name': 'Ayton',
  'is_active': True},
 {'id': 1628962,
  'full_name': 'Udoka Azubuike',
  'first_name': 'Udoka',
  'last_name': 'Azubuike',
  'is_active': True},
 {'id': 1630641,
  'full_name': 'Ibou Badji',
  'first_name': 'Ibou',
  'last_name': 'Badji',
  'is_active': True},
 {'id': 1628963,
  'full_name': 'Marvin Bagley III',
  'first_name': 'Marvin',
  'last_name': 'Bagley III',
  'is_active': True},
 {'id': 1641735,
  'full_name': 'Amari Bailey',
  'first_name': 'Amari',
  'last_name': 'Bailey',
  'is_active': True},
 {'id': 1631116,
  'full_name': 'Patrick Baldwin Jr.',
  'first_name': 'Patrick',
  'last_name': 'Baldwin Jr.',
  'is_active': True},
 {'id': 1630163,
  'full_name': 'LaMelo Ball',
  'first_name': 'LaMelo',
  'last_name': 'Ball',
  'is_active': True},
 {'id': 1628964,
  'full_name': 'Mo Bamba',
  'first_name': 'Mo',
  'last_name': 'Bamba',
  'is_active': True},
 {'id': 1631094,
  'full_name': 'Paolo Banchero',
  'first_name': 'Paolo',
  'last_name': 'Banchero',
  'is_active': True},
 {'id': 1630217,
  'full_name': 'Desmond Bane',
  'first_name': 'Desmond',
  'last_name': 'Bane',
  'is_active': True},
 {'id': 1630625,
  'full_name': 'Dalano Banton',
  'first_name': 'Dalano',
  'last_name': 'Banton',
  'is_active': True},
 {'id': 1631230,
  'full_name': 'Dominick Barlow',
  'first_name': 'Dominick',
  'last_name': 'Barlow',
  'is_active': True},
 {'id': 203084,
  'full_name': 'Harrison Barnes',
  'first_name': 'Harrison',
  'last_name': 'Barnes',
  'is_active': True},
 {'id': 1630567,
  'full_name': 'Scottie Barnes',
  'first_name': 'Scottie',
  'last_name': 'Barnes',
  'is_active': True},
 {'id': 1629628,
  'full_name': 'RJ Barrett',
  'first_name': 'RJ',
  'last_name': 'Barrett',
  'is_active': True},
 {'id': 1629646,
  'full_name': 'Charles Bassey',
  'first_name': 'Charles',
  'last_name': 'Bassey',
  'is_active': True},
 {'id': 1641734,
  'full_name': 'Emoni Bates',
  'first_name': 'Emoni',
  'last_name': 'Bates',
  'is_active': True},
 {'id': 1628966,
  'full_name': 'Keita Bates-Diop',
  'first_name': 'Keita',
  'last_name': 'Bates-Diop',
  'is_active': True},
 {'id': 201587,
  'full_name': 'Nicolas Batum',
  'first_name': 'Nicolas',
  'last_name': 'Batum',
  'is_active': True},
 {'id': 1629647,
  'full_name': 'Darius Bazley',
  'first_name': 'Darius',
  'last_name': 'Bazley',
  'is_active': True},
 {'id': 203078,
  'full_name': 'Bradley Beal',
  'first_name': 'Bradley',
  'last_name': 'Beal',
  'is_active': True},
 {'id': 1627736,
  'full_name': 'Malik Beasley',
  'first_name': 'Malik',
  'last_name': 'Beasley',
  'is_active': True},
 {'id': 1630699,
  'full_name': 'MarJon Beauchamp',
  'first_name': 'MarJon',
  'last_name': 'Beauchamp',
  'is_active': True},
 {'id': 1631262,
  'full_name': 'Jules Bernard',
  'first_name': 'Jules',
  'last_name': 'Bernard',
  'is_active': True},
 {'id': 202722,
  'full_name': 'Davis Bertans',
  'first_name': 'Davis',
  'last_name': 'Bertans',
  'is_active': True},
 {'id': 201976,
  'full_name': 'Patrick Beverley',
  'first_name': 'Patrick',
  'last_name': 'Beverley',
  'is_active': True},
 {'id': 1630180,
  'full_name': 'Saddiq Bey',
  'first_name': 'Saddiq',
  'last_name': 'Bey',
  'is_active': True},
 {'id': 1629048,
  'full_name': 'Goga Bitadze',
  'first_name': 'Goga',
  'last_name': 'Bitadze',
  'is_active': True},
 {'id': 1641931,
  'full_name': 'Onuralp Bitim',
  'first_name': 'Onuralp',
  'last_name': 'Bitim',
  'is_active': True},
 {'id': 202687,
  'full_name': 'Bismack Biyombo',
  'first_name': 'Bismack',
  'last_name': 'Biyombo',
  'is_active': True},
 {'id': 1641710,
  'full_name': 'Anthony Black',
  'first_name': 'Anthony',
  'last_name': 'Black',
  'is_active': True},
 {'id': 1641778,
  'full_name': 'Leaky Black',
  'first_name': 'Leaky',
  'last_name': 'Black',
  'is_active': True},
 {'id': 1631205,
  'full_name': 'Buddy Boeheim',
  'first_name': 'Buddy',
  'last_name': 'Boeheim',
  'is_active': True},
 {'id': 203992,
  'full_name': 'Bogdan Bogdanovic',
  'first_name': 'Bogdan',
  'last_name': 'Bogdanovic',
  'is_active': True},
 {'id': 202711,
  'full_name': 'Bojan Bogdanovic',
  'first_name': 'Bojan',
  'last_name': 'Bogdanovic',
  'is_active': True},
 {'id': 1629626,
  'full_name': 'Bol Bol',
  'first_name': 'Bol',
  'last_name': 'Bol',
  'is_active': True},
 {'id': 1629716,
  'full_name': 'Marques Bolden',
  'first_name': 'Marques',
  'last_name': 'Bolden',
  'is_active': True},
 {'id': 1626164,
  'full_name': 'Devin Booker',
  'first_name': 'Devin',
  'last_name': 'Booker',
  'is_active': True},
 {'id': 1630527,
  'full_name': 'Brandon Boston Jr.',
  'first_name': 'Brandon',
  'last_name': 'Boston Jr.',
  'is_active': True},
 {'id': 1628449,
  'full_name': 'Chris Boucher',
  'first_name': 'Chris',
  'last_name': 'Boucher',
  'is_active': True},
 {'id': 1630547,
  'full_name': 'James Bouknight',
  'first_name': 'James',
  'last_name': 'Bouknight',
  'is_active': True},
 {'id': 1631123,
  'full_name': 'Jamaree Bouyea',
  'first_name': 'Jamaree',
  'last_name': 'Bouyea',
  'is_active': True},
 {'id': 1631103,
  'full_name': 'Malaki Branham',
  'first_name': 'Malaki',
  'last_name': 'Branham',
  'is_active': True},
 {'id': 1631128,
  'full_name': 'Christian Braun',
  'first_name': 'Christian',
  'last_name': 'Braun',
  'is_active': True},
 {'id': 1628969,
  'full_name': 'Mikal Bridges',
  'first_name': 'Mikal',
  'last_name': 'Bridges',
  'is_active': True},
 {'id': 1628970,
  'full_name': 'Miles Bridges',
  'first_name': 'Miles',
  'last_name': 'Bridges',
  'is_active': True},
 {'id': 1629052,
  'full_name': 'Oshae Brissett',
  'first_name': 'Oshae',
  'last_name': 'Brissett',
  'is_active': True},
 {'id': 1631167,
  'full_name': 'Izaiah Brockington',
  'first_name': 'Izaiah',
  'last_name': 'Brockington',
  'is_active': True},
 {'id': 1627763,
  'full_name': 'Malcolm Brogdon',
  'first_name': 'Malcolm',
  'last_name': 'Brogdon',
  'is_active': True},
 {'id': 1629717,
  'full_name': 'Armoni Brooks',
  'first_name': 'Armoni',
  'last_name': 'Brooks',
  'is_active': True},
 {'id': 1628415,
  'full_name': 'Dillon Brooks',
  'first_name': 'Dillon',
  'last_name': 'Brooks',
  'is_active': True},
 {'id': 1628971,
  'full_name': 'Bruce Brown',
  'first_name': 'Bruce',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1627759,
  'full_name': 'Jaylen Brown',
  'first_name': 'Jaylen',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1631112,
  'full_name': 'Kendall Brown',
  'first_name': 'Kendall',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1641738,
  'full_name': 'Kobe Brown',
  'first_name': 'Kobe',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1629650,
  'full_name': 'Moses Brown',
  'first_name': 'Moses',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1630535,
  'full_name': 'Greg Brown III',
  'first_name': 'Greg',
  'last_name': 'Brown III',
  'is_active': True},
 {'id': 1629718,
  'full_name': 'Charlie Brown Jr.',
  'first_name': 'Charlie',
  'last_name': 'Brown Jr.',
  'is_active': True},
 {'id': 1628972,
  'full_name': 'Troy Brown Jr.',
  'first_name': 'Troy',
  'last_name': 'Brown Jr.',
  'is_active': True},
 {'id': 1628973,
  'full_name': 'Jalen Brunson',
  'first_name': 'Jalen',
  'last_name': 'Brunson',
  'is_active': True},
 {'id': 1628418,
  'full_name': 'Thomas Bryant',
  'first_name': 'Thomas',
  'last_name': 'Bryant',
  'is_active': True},
 {'id': 1641723,
  'full_name': 'Kobe Bufkin',
  'first_name': 'Kobe',
  'last_name': 'Bufkin',
  'is_active': True},
 {'id': 203493,
  'full_name': 'Reggie Bullock Jr.',
  'first_name': 'Reggie',
  'last_name': 'Bullock Jr.',
  'is_active': True},
 {'id': 202692,
  'full_name': 'Alec Burks',
  'first_name': 'Alec',
  'last_name': 'Burks',
  'is_active': True},
 {'id': 1630215,
  'full_name': 'Jared Butler',
  'first_name': 'Jared',
  'last_name': 'Butler',
  'is_active': True},
 {'id': 202710,
  'full_name': 'Jimmy Butler',
  'first_name': 'Jimmy',
  'last_name': 'Butler',
  'is_active': True},
 {'id': 1631288,
  'full_name': 'Jamal Cain',
  'first_name': 'Jamal',
  'last_name': 'Cain',
  'is_active': True},
 {'id': 203484,
  'full_name': 'Kentavious Caldwell-Pope',
  'first_name': 'Kentavious',
  'last_name': 'Caldwell-Pope',
  'is_active': True},
 {'id': 1641739,
  'full_name': 'Toumani Camara',
  'first_name': 'Toumani',
  'last_name': 'Camara',
  'is_active': True},
 {'id': 203991,
  'full_name': 'Clint Capela',
  'first_name': 'Clint',
  'last_name': 'Capela',
  'is_active': True},
 {'id': 1628975,
  'full_name': 'Jevon Carter',
  'first_name': 'Jevon',
  'last_name': 'Carter',
  'is_active': True},
 {'id': 1628976,
  'full_name': 'Wendell Carter Jr.',
  'first_name': 'Wendell',
  'last_name': 'Carter Jr.',
  'is_active': True},
 {'id': 1630618,
  'full_name': 'DJ Carton',
  'first_name': 'DJ',
  'last_name': 'Carton',
  'is_active': True},
 {'id': 1627936,
  'full_name': 'Alex Caruso',
  'first_name': 'Alex',
  'last_name': 'Caruso',
  'is_active': True},
 {'id': 1630658,
  'full_name': 'Colin Castleton',
  'first_name': 'Colin',
  'last_name': 'Castleton',
  'is_active': True},
 {'id': 1630608,
  'full_name': 'Malcolm Cazalon',
  'first_name': 'Malcolm',
  'last_name': 'Cazalon',
  'is_active': True},
 {'id': 1630577,
  'full_name': 'Julian Champagnie',
  'first_name': 'Julian',
  'last_name': 'Champagnie',
  'is_active': True},
 {'id': 1630551,
  'full_name': 'Justin Champagnie',
  'first_name': 'Justin',
  'last_name': 'Champagnie',
  'is_active': True},
 {'id': 1631108,
  'full_name': 'Max Christie',
  'first_name': 'Max',
  'last_name': 'Christie',
  'is_active': True},
 {'id': 1631321,
  'full_name': 'Sidy Cissoko',
  'first_name': 'Sidy',
  'last_name': 'Cissoko',
  'is_active': True},
 {'id': 1629634,
  'full_name': 'Brandon Clarke',
  'first_name': 'Brandon',
  'last_name': 'Clarke',
  'is_active': True},
 {'id': 203903,
  'full_name': 'Jordan Clarkson',
  'first_name': 'Jordan',
  'last_name': 'Clarkson',
  'is_active': True},
 {'id': 1629651,
  'full_name': 'Nic Claxton',
  'first_name': 'Nic',
  'last_name': 'Claxton',
  'is_active': True},
 {'id': 1641730,
  'full_name': 'Noah Clowney',
  'first_name': 'Noah',
  'last_name': 'Clowney',
  'is_active': True},
 {'id': 1629599,
  'full_name': 'Amir Coffey',
  'first_name': 'Amir',
  'last_name': 'Coffey',
  'is_active': True},
 {'id': 1628381,
  'full_name': 'John Collins',
  'first_name': 'John',
  'last_name': 'Collins',
  'is_active': True},
 {'id': 1628380,
  'full_name': 'Zach Collins',
  'first_name': 'Zach',
  'last_name': 'Collins',
  'is_active': True},
 {'id': 201144,
  'full_name': 'Mike Conley',
  'first_name': 'Mike',
  'last_name': 'Conley',
  'is_active': True},
 {'id': 1626192,
  'full_name': 'Pat Connaughton',
  'first_name': 'Pat',
  'last_name': 'Connaughton',
  'is_active': True},
 {'id': 1641731,
  'full_name': 'Bilal Coulibaly',
  'first_name': 'Bilal',
  'last_name': 'Coulibaly',
  'is_active': True},
 {'id': 1641741,
  'full_name': 'Ricky Council IV',
  'first_name': 'Ricky',
  'last_name': 'Council IV',
  'is_active': True},
 {'id': 203496,
  'full_name': 'Robert Covington',
  'first_name': 'Robert',
  'last_name': 'Covington',
  'is_active': True},
 {'id': 1628470,
  'full_name': 'Torrey Craig',
  'first_name': 'Torrey',
  'last_name': 'Craig',
  'is_active': True},
 {'id': 203109,
  'full_name': 'Jae Crowder',
  'first_name': 'Jae',
  'last_name': 'Crowder',
  'is_active': True},
 {'id': 1630622,
  'full_name': 'Jalen Crutcher',
  'first_name': 'Jalen',
  'last_name': 'Crutcher',
  'is_active': True},
 {'id': 1630595,
  'full_name': 'Cade Cunningham',
  'first_name': 'Cade',
  'last_name': 'Cunningham',
  'is_active': True},
 {'id': 203552,
  'full_name': 'Seth Curry',
  'first_name': 'Seth',
  'last_name': 'Curry',
  'is_active': True},
 {'id': 201939,
  'full_name': 'Stephen Curry',
  'first_name': 'Stephen',
  'last_name': 'Curry',
  'is_active': True},
 {'id': 1630700,
  'full_name': 'Dyson Daniels',
  'first_name': 'Dyson',
  'last_name': 'Daniels',
  'is_active': True},
 {'id': 203076,
  'full_name': 'Anthony Davis',
  'first_name': 'Anthony',
  'last_name': 'Davis',
  'is_active': True},
 {'id': 1631098,
  'full_name': 'Johnny Davis',
  'first_name': 'Johnny',
  'last_name': 'Davis',
  'is_active': True},
 {'id': 1631120,
  'full_name': 'JD Davison',
  'first_name': 'JD',
  'last_name': 'Davison',
  'is_active': True},
 {'id': 201942,
  'full_name': 'DeMar DeRozan',
  'first_name': 'DeMar',
  'last_name': 'DeRozan',
  'is_active': True},
 {'id': 1641926,
  'full_name': 'Dexter Dennis',
  'first_name': 'Dexter',
  'last_name': 'Dennis',
  'is_active': True},
 {'id': 1628978,
  'full_name': 'Donte DiVincenzo',
  'first_name': 'Donte',
  'last_name': 'DiVincenzo',
  'is_active': True},
 {'id': 1631217,
  'full_name': 'Moussa Diabate',
  'first_name': 'Moussa',
  'last_name': 'Diabate',
  'is_active': True},
 {'id': 1629603,
  'full_name': 'Mamadi Diakite',
  'first_name': 'Mamadi',
  'last_name': 'Diakite',
  'is_active': True},
 {'id': 1628977,
  'full_name': 'Hamidou Diallo',
  'first_name': 'Hamidou',
  'last_name': 'Diallo',
  'is_active': True},
 {'id': 1641711,
  'full_name': 'Gradey Dick',
  'first_name': 'Gradey',
  'last_name': 'Dick',
  'is_active': True},
 {'id': 1631172,
  'full_name': 'Ousmane Dieng',
  'first_name': 'Ousmane',
  'last_name': 'Dieng',
  'is_active': True},
 {'id': 203915,
  'full_name': 'Spencer Dinwiddie',
  'first_name': 'Spencer',
  'last_name': 'Dinwiddie',
  'is_active': True},
 {'id': 1629029,
  'full_name': 'Luka Doncic',
  'first_name': 'Luka',
  'last_name': 'Doncic',
  'is_active': True},
 {'id': 1629652,
  'full_name': 'Luguentz Dort',
  'first_name': 'Luguentz',
  'last_name': 'Dort',
  'is_active': True},
 {'id': 1630245,
  'full_name': 'Ayo Dosunmu',
  'first_name': 'Ayo',
  'last_name': 'Dosunmu',
  'is_active': True},
 {'id': 1630288,
  'full_name': 'Jeff Dowtin Jr.',
  'first_name': 'Jeff',
  'last_name': 'Dowtin Jr.',
  'is_active': True},
 {'id': 1630929,
  'full_name': 'Henri Drell',
  'first_name': 'Henri',
  'last_name': 'Drell',
  'is_active': True},
 {'id': 203083,
  'full_name': 'Andre Drummond',
  'first_name': 'Andre',
  'last_name': 'Drummond',
  'is_active': True},
 {'id': 1630537,
  'full_name': 'Chris Duarte',
  'first_name': 'Chris',
  'last_name': 'Duarte',
  'is_active': True},
 {'id': 1630561,
  'full_name': 'David Duke Jr.',
  'first_name': 'David',
  'last_name': 'Duke Jr.',
  'is_active': True},
 {'id': 1627739,
  'full_name': 'Kris Dunn',
  'first_name': 'Kris',
  'last_name': 'Dunn',
  'is_active': True},
 {'id': 201142,
  'full_name': 'Kevin Durant',
  'first_name': 'Kevin',
  'last_name': 'Durant',
  'is_active': True},
 {'id': 1631105,
  'full_name': 'Jalen Duren',
  'first_name': 'Jalen',
  'last_name': 'Duren',
  'is_active': True},
 {'id': 1631106,
  'full_name': 'Tari Eason',
  'first_name': 'Tari',
  'last_name': 'Eason',
  'is_active': True},
 {'id': 1630162,
  'full_name': 'Anthony Edwards',
  'first_name': 'Anthony',
  'last_name': 'Edwards',
  'is_active': True},
 {'id': 1630556,
  'full_name': 'Kessler Edwards',
  'first_name': 'Kessler',
  'last_name': 'Edwards',
  'is_active': True},
 {'id': 1631165,
  'full_name': 'Keon Ellis',
  'first_name': 'Keon',
  'last_name': 'Ellis',
  'is_active': True},
 {'id': 203954,
  'full_name': 'Joel Embiid',
  'first_name': 'Joel',
  'last_name': 'Embiid',
  'is_active': True},
 {'id': 1629234,
  'full_name': 'Drew Eubanks',
  'first_name': 'Drew',
  'last_name': 'Eubanks',
  'is_active': True},
 {'id': 1641787,
  'full_name': 'Tosan Evbuomwan',
  'first_name': 'Tosan',
  'last_name': 'Evbuomwan',
  'is_active': True},
 {'id': 203957,
  'full_name': 'Dante Exum',
  'first_name': 'Dante',
  'last_name': 'Exum',
  'is_active': True},
 {'id': 1628981,
  'full_name': 'Bruno Fernando',
  'first_name': 'Bruno',
  'last_name': 'Fernando',
  'is_active': True},
 {'id': 1627827,
  'full_name': 'Dorian Finney-Smith',
  'first_name': 'Dorian',
  'last_name': 'Finney-Smith',
  'is_active': True},
 {'id': 1641745,
  'full_name': 'Adam Flagler',
  'first_name': 'Adam',
  'last_name': 'Flagler',
  'is_active': True},
 {'id': 1630201,
  'full_name': 'Malachi Flynn',
  'first_name': 'Malachi',
  'last_name': 'Flynn',
  'is_active': True},
 {'id': 1631323,
  'full_name': 'Simone Fontecchio',
  'first_name': 'Simone',
  'last_name': 'Fontecchio',
  'is_active': True},
 {'id': 1630259,
  'full_name': 'Jordan Ford',
  'first_name': 'Jordan',
  'last_name': 'Ford',
  'is_active': True},
 {'id': 1630235,
  'full_name': 'Trent Forrest',
  'first_name': 'Trent',
  'last_name': 'Forrest',
  'is_active': True},
 {'id': 203095,
  'full_name': 'Evan Fournier',
  'first_name': 'Evan',
  'last_name': 'Fournier',
  'is_active': True},
 {'id': 1628368,
  'full_name': "De'Aaron Fox",
  'first_name': "De'Aaron",
  'last_name': 'Fox',
  'is_active': True},
 {'id': 1631241,
  'full_name': 'Javon Freeman-Liberty',
  'first_name': 'Javon',
  'last_name': 'Freeman-Liberty',
  'is_active': True},
 {'id': 1641788,
  'full_name': 'Alex Fudge',
  'first_name': 'Alex',
  'last_name': 'Fudge',
  'is_active': True},
 {'id': 1628365,
  'full_name': 'Markelle Fultz',
  'first_name': 'Markelle',
  'last_name': 'Fultz',
  'is_active': True},
 {'id': 1641847,
  'full_name': 'Andrew Funk',
  'first_name': 'Andrew',
  'last_name': 'Funk',
  'is_active': True},
 {'id': 1629117,
  'full_name': 'Wenyen Gabriel',
  'first_name': 'Wenyen',
  'last_name': 'Gabriel',
  'is_active': True},
 {'id': 1629655,
  'full_name': 'Daniel Gafford',
  'first_name': 'Daniel',
  'last_name': 'Gafford',
  'is_active': True},
 {'id': 201568,
  'full_name': 'Danilo Gallinari',
  'first_name': 'Danilo',
  'last_name': 'Gallinari',
  'is_active': True},
 {'id': 1641945,
  'full_name': 'Jaylin Galloway',
  'first_name': 'Jaylin',
  'last_name': 'Galloway',
  'is_active': True},

In [8]:
df_pro_players = pd.DataFrame(pro_players)

In [9]:
df_pro_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          573 non-null    int64
 1   full_name   573 non-null    object
 2   first_name  573 non-null    object
 3   last_name   573 non-null    object
 4   is_active   573 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 18.6+ KB

In [10]:
df_pro_players

          id                 full_name first_name         last_name  is_active
0    1630173          Precious Achiuwa   Precious           Achiuwa       True
1    1628389               Bam Adebayo        Bam           Adebayo       True
2    1630534              Ochai Agbaji      Ochai            Agbaji       True
3    1630583              Santi Aldama      Santi            Aldama       True
4    1629638  Nickeil Alexander-Walker    Nickeil  Alexander-Walker       True
..       ...                       ...        ...               ...        ...
568   201152            Thaddeus Young   Thaddeus             Young       True
569  1629027                Trae Young       Trae             Young       True
570  1630209            Omer Yurtseven       Omer         Yurtseven       True
571   203469               Cody Zeller       Cody            Zeller       True
572  1627826               Ivica Zubac      Ivica             Zubac       True

[573 rows x 5 columns]

In [11]:
df_pro_players[df_pro_players['full_name'] == 'Mikal Bridges']

         id      full_name first_name last_name  is_active
60  1628969  Mikal Bridges      Mikal   Bridges       True

In [12]:
pro_stats = nba_stats.PlayerCareerStats

NBA API doesn't have the most extensive college stats, need to access some other API for that

Possibly going to manually download data from sports reference since they don't have an official API.

Since I limited scope to active players only, need to figure out how far back I should look in terms of college stats.

will limit college stats to big 10 conference

In [13]:
from nba_api.stats.endpoints import commonallplayers

In [14]:
active_players = commonallplayers.CommonAllPlayers(is_only_current_season=1)

In [15]:
players_general_data = active_players.get_data_frames()[0]
players_general_data

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_SLUG,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,1630173,"Achiuwa, Precious",Precious Achiuwa,1,2020,2024,precious_achiuwa,precious_achiuwa,1610612752,New York,Knicks,NYK,knicks,knicks,Y,00
1,203500,"Adams, Steven",Steven Adams,1,2013,2024,steven_adams,steven_adams,1610612745,Houston,Rockets,HOU,rockets,rockets,Y,00
2,1628389,"Adebayo, Bam",Bam Adebayo,1,2017,2024,bam_adebayo,bam_adebayo,1610612748,Miami,Heat,MIA,heat,heat,Y,00
3,1630534,"Agbaji, Ochai",Ochai Agbaji,1,2022,2024,ochai_agbaji,ochai_agbaji,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
4,1630583,"Aldama, Santi",Santi Aldama,1,2021,2024,santi_aldama,santi_aldama,1610612763,Memphis,Grizzlies,MEM,grizzlies,grizzlies,Y,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,203469,"Zeller, Cody",Cody Zeller,1,2013,2024,cody_zeller,cody_zeller,1610612737,Atlanta,Hawks,ATL,hawks,hawks,Y,00
518,1627826,"Zubac, Ivica",Ivica Zubac,1,2016,2024,ivica_zubac,ivica_zubac,1610612746,LA,Clippers,LAC,clippers,clippers,Y,01
519,1641783,"da Silva, Tristan",Tristan da Silva,1,2024,2024,tristan_da_silva,tristan_da_silva,1610612753,Orlando,Magic,ORL,magic,magic,Y,00
520,1628427,"Čančar, Vlatko",Vlatko Čančar,1,2019,2024,vlatko_cancar,vlatko_čančar,1610612743,Denver,Nuggets,DEN,nuggets,nuggets,Y,01
521,203967,"Šarić, Dario",Dario Šarić,1,2016,2024,dario_saric,dario_šarić,1610612743,Denver,Nuggets,DEN,nuggets,nuggets,Y,00

In [16]:
players_general_data[players_general_data['DISPLAY_FIRST_LAST'] == 'Mikal Bridges']

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_SLUG,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
49,1628969,"Bridges, Mikal",Mikal Bridges,1,2018,2024,mikal_bridges,mikal_bridges,1610612752,New York,Knicks,NYK,knicks,knicks,Y,00

In [17]:
players_general_data.columns

Index(['PERSON_ID', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FIRST_LAST',
       'ROSTERSTATUS', 'FROM_YEAR', 'TO_YEAR', 'PLAYERCODE', 'PLAYER_SLUG',
       'TEAM_ID', 'TEAM_CITY', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_SLUG',
       'TEAM_CODE', 'GAMES_PLAYED_FLAG', 'OTHERLEAGUE_EXPERIENCE_CH'],
      dtype='object')

In [18]:
columns = ['PERSON_ID', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FIRST_LAST',
       'ROSTERSTATUS', 'FROM_YEAR', 'TO_YEAR', 'PLAYERCODE', 'PLAYER_SLUG',
       'TEAM_ID', 'TEAM_CITY', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_SLUG',
       'TEAM_CODE', 'GAMES_PLAYED_FLAG', 'OTHERLEAGUE_EXPERIENCE_CH']

In [19]:
columns = [column.lower() for column in columns]

In [20]:
players_general_data.columns = columns

In [21]:
players_general_data

,person_id,display_last_comma_first,display_first_last,rosterstatus,from_year,to_year,playercode,player_slug,team_id,team_city,team_name,team_abbreviation,team_slug,team_code,games_played_flag,otherleague_experience_ch
0,1630173,"Achiuwa, Precious",Precious Achiuwa,1,2020,2024,precious_achiuwa,precious_achiuwa,1610612752,New York,Knicks,NYK,knicks,knicks,Y,00
1,203500,"Adams, Steven",Steven Adams,1,2013,2024,steven_adams,steven_adams,1610612745,Houston,Rockets,HOU,rockets,rockets,Y,00
2,1628389,"Adebayo, Bam",Bam Adebayo,1,2017,2024,bam_adebayo,bam_adebayo,1610612748,Miami,Heat,MIA,heat,heat,Y,00
3,1630534,"Agbaji, Ochai",Ochai Agbaji,1,2022,2024,ochai_agbaji,ochai_agbaji,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
4,1630583,"Aldama, Santi",Santi Aldama,1,2021,2024,santi_aldama,santi_aldama,1610612763,Memphis,Grizzlies,MEM,grizzlies,grizzlies,Y,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,203469,"Zeller, Cody",Cody Zeller,1,2013,2024,cody_zeller,cody_zeller,1610612737,Atlanta,Hawks,ATL,hawks,hawks,Y,00
518,1627826,"Zubac, Ivica",Ivica Zubac,1,2016,2024,ivica_zubac,ivica_zubac,1610612746,LA,Clippers,LAC,clippers,clippers,Y,01
519,1641783,"da Silva, Tristan",Tristan da Silva,1,2024,2024,tristan_da_silva,tristan_da_silva,1610612753,Orlando,Magic,ORL,magic,magic,Y,00
520,1628427,"Čančar, Vlatko",Vlatko Čančar,1,2019,2024,vlatko_cancar,vlatko_čančar,1610612743,Denver,Nuggets,DEN,nuggets,nuggets,Y,01
521,203967,"Šarić, Dario",Dario Šarić,1,2016,2024,dario_saric,dario_šarić,1610612743,Denver,Nuggets,DEN,nuggets,nuggets,Y,00

In [22]:
player_ids = players_general_data['person_id'].to_list()

In [23]:
player_ids[:5]

[1630173, 203500, 1628389, 1630534, 1630583]

In [24]:
player_stats = []

In [25]:
'''

import time
import random
DOWNLOAD_DELAY = 5

def fetch_player_stats(player_id, retries=3, delay=5):
    for attempt in range(retries):
        time.sleep(random.uniform(0,DOWNLOAD_DELAY))
        try:
            # Fetch player career stats
            player_stats = nba_stats.PlayerCareerStats(player_id=player_id)
            return player_stats.get_data_frames()[0]  # Return player stats dataframe
        except Exception as e:
            print(f"Attempt {attempt + 1} failed for Player ID {player_id}: {e}")
            time.sleep(delay)
    return None

'''

'\n\nimport time\nimport random\nDOWNLOAD_DELAY = 5\n\ndef fetch_player_stats(player_id, retries=3, delay=5):\n    for attempt in range(retries):\n        time.sleep(random.uniform(0,DOWNLOAD_DELAY))\n        try:\n            # Fetch player career stats\n            player_stats = nba_stats.PlayerCareerStats(player_id=player_id)\n            return player_stats.get_data_frames()[0]  # Return player stats dataframe\n        except Exception as e:\n            print(f"Attempt {attempt + 1} failed for Player ID {player_id}: {e}")\n            time.sleep(delay)\n    return None\n\n'

In [26]:
'''
for player_id in player_ids:
    player_stats_df = fetch_player_stats(player_id)
'''

'\nfor player_id in player_ids:\n    player_stats_df = fetch_player_stats(player_id)\n'

In [27]:
players_general_data[players_general_data['person_id'] == 203967]

,person_id,display_last_comma_first,display_first_last,rosterstatus,from_year,to_year,playercode,player_slug,team_id,team_city,team_name,team_abbreviation,team_slug,team_code,games_played_flag,otherleague_experience_ch
521,203967,"Šarić, Dario",Dario Šarić,1,2016,2024,dario_saric,dario_šarić,1610612743,Denver,Nuggets,DEN,nuggets,nuggets,Y,00

In [28]:
'''
even for 5 player ids, it won't work

for id in player_ids[:5]:
    player_stats = nba_stats.PlayerCareerStats(player_id=id)
'''

"\neven for 5 player ids, it won't work\n\nfor id in player_ids[:5]:\n    player_stats = nba_stats.PlayerCareerStats(player_id=id)\n"

I'm trying to use the player_id column in the general player dataframe to loop through all active players ids, this way I can get all players stats in one dataframe. It looks like the API can't handle it for some reason so I'll be trying another way.

In [29]:
from nba_api.stats.endpoints import leaguegamefinder

In [30]:
gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable='2022-2023')

KeyError: 'resultSet'

In [ ]:
players_general_data[players_general_data['playercode'] == 'lebron_james']

,person_id,display_last_comma_first,display_first_last,rosterstatus,from_year,to_year,playercode,player_slug,team_id,team_city,team_name,team_abbreviation,team_slug,team_code,games_played_flag,otherleague_experience_ch
253,2544,"James, LeBron",LeBron James,1,2003,2024,lebron_james,lebron_james,1610612747,Los Angeles,Lakers,LAL,lakers,lakers,Y,00

In [ ]:
lbj = nba_stats.PlayerCareerStats(player_id='2544')
lbj.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,...,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,...,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,56,56,2084.0,640,...,0.756,63,396,459,349,73,59,196,121,1695
19,2544,2022-23,00,1610612747,LAL,38.0,55,54,1954.0,609,...,0.768,65,392,457,375,50,32,178,88,1590
20,2544,2023-24,00,1610612747,LAL,39.0,71,71,2504.0,685,...,0.750,61,457,518,589,89,38,245,78,1822

In [ ]:
mikal = nba_stats.PlayerCareerStats(player_id='1628969')
mikal.career_totals_college_season.get_data_frame()

,PLAYER_ID,LEAGUE_ID,ORGANIZATION_ID,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628969,00,0,116,73,3172,458,873,0.525,171,...,0.845,131,372,503,183,163,101,124,257,1311

In [ ]:
mikal.get_available_data()

dict_keys(['SeasonTotalsRegularSeason', 'CareerTotalsRegularSeason', 'SeasonTotalsPostSeason', 'CareerTotalsPostSeason', 'SeasonTotalsAllStarSeason', 'CareerTotalsAllStarSeason', 'SeasonTotalsCollegeSeason', 'CareerTotalsCollegeSeason', 'SeasonTotalsShowcaseSeason', 'CareerTotalsShowcaseSeason', 'SeasonRankingsRegularSeason', 'SeasonRankingsPostSeason'])

Didn't realize there's a function here that lets you see what specific data you'd like to access. Maybe it'll be easier to congregate everybody's career totals into one dataframe

I also think I should limit my scope again. Looking at Mikal's totals made me realize that I shouldn't take rookies or sophomores into account. Since data for 3rd year players and above have more than likely shown their potential.

In [ ]:
mikal_df = mikal.get_data_frames()[1]

In [ ]:
mikal_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PLAYER_ID  1 non-null      int64
 1   LEAGUE_ID  1 non-null      object
 2   Team_ID    1 non-null      int64
 3   GP         1 non-null      int64
 4   GS         1 non-null      int64
 5   MIN        1 non-null      float64
 6   FGM        1 non-null      int64
 7   FGA        1 non-null      int64
 8   FG_PCT     1 non-null      float64
 9   FG3M       1 non-null      int64
 10  FG3A       1 non-null      int64
 11  FG3_PCT    1 non-null      float64
 12  FTM        1 non-null      int64
 13  FTA        1 non-null      int64
 14  FT_PCT     1 non-null      float64
 15  OREB       1 non-null      int64
 16  DREB       1 non-null      int64
 17  REB        1 non-null      int64
 18  AST        1 non-null      int64
 19  STL        1 non-null      int64
 20  BLK        1 non-null      int64
 21  TOV        1 non-null      int64
 22  PF         1 non-null      int64
 23  PTS        1 non-null      int64
dtypes: float64(4), int64(19), object(1)
memory usage: 320.0+ bytes

In [ ]:
mikal_df.columns

Index(['PLAYER_ID', 'LEAGUE_ID', 'Team_ID', 'GP', 'GS', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')